
name: CI

on:
  push:
    branches: 
       - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Node version
        uses: actions/setup-node@v3
      - name: Install Software
        run: |
             sudo apt update
             sudo apt install -y nodejs npm
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
         repository: Pasechnyktanya/dofd-05-node-Pasechnyktanya-main
         ref: main
      - name: Clone Project
        run: git clone https://github.com/Pasechnyktanya/dofd-05-node-Pasechnyktanya-main
      - name: Install dependencies
        run: npm install 
      - name: Build Project
        run: npm run build 
      
      - name: Run Unit Tests
        run: npm test

    
     
