
name: CI

on:
  push:
    branches: 
       - main
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Use custom node version
        uses: actions/setup-node@v3
        with:
         node-version: 16
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
         repository: Pasechnyktanya/dofd-05-node-Pasechnyktanya-main
         ref: main
      - name: Install dependencies
        run: "npm install --legacy-peer-deps"
      - name: Test
        run: "npm test"

  
     
